export { default as About } from './About'
export { default as Base } from './Base'
export { default as Home } from './Home'
export { default as Posts } from './Posts'
export { default as Tips } from './Tips'
